version: "3.7"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: build-stage
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - BACKEND_SERVICE_URL=http://127.0.0.1:5000
      - VUE_GATEWAY_URL=http://127.0.0.1:8080
    volumes:
      - vue_app:/app
    networks:
      - api_bridge

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: build-stage
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/users_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      - db
    networks:
      - api_bridge
    restart: always

  db:
    build:
      context: backend/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - users_data:/var/lib/postgresql/data/
    networks:
      - api_bridge

  nginx:
      build:
        context: nginx
        dockerfile: Dockerfile
      restart: always
      ports:
        - 80:80
      depends_on:
        - backend
        - frontend
      networks:
        - api_bridge

networks:
  api_bridge:
    driver: bridge

volumes:
  users_data:
  vue_app:

    
